### ISSUE TITLE
Create a new release 

### ISSUE THREAD

**Issue by FlorianMichael** [astei/krypton#101]
Constantly people complain to ViaFabricPlus that the mod is not compatible with Krypton, so it would be nice if you could make a new release on Curseforge/Modrinth and Github with the API changes, I have already implemented the API and fixed the incompatibility, and since the mod is as it looks anyway dead, that should be no problem to make a release, because I'm tired of always explaining to people why it is incompatible and so on.

**Comment by astei** [comment]
Minecraft is not my full time job.

The reason why there hasn’t been a release is because outside of the pipeline event change I made to accommodate your mod, there hasn’t been much else of note. I generally don’t cut very small releases unless I have to.

A release will come. Don’t demand I make a release.

**Comment by astei** [comment]
0.2.3 is now out. In this case, a new version of Minecraft came out, so it was a natural time to make a release.
