### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [astei/krypton#122]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

**Comment by flikrheist** [comment]
@NXTler | Hello NXTler, If the specific version is hosted on Modrinth, you are allowed to use it in your modpack, In fact, any project on Modrinth can be used in your modpack no matter what it it licenced under.

https://support.modrinth.com/en/articles/8797527-obtaining-modpack-permissions"

**Comment by flikrheist** [comment]
@NXTler | Are you available to collaborate?

**Comment by NXTler** [comment]
I was busy irl so I didn't see your invite on Modrinth until now. I would like to have a few more details on why I should join before making a decision, Discord dms are open if you prefer to discuss this in private.

**Comment by flikrheist** [comment]
@NXTler | I'd just appreciate someone who could just help me test, create and edit my projects and collab together. We both have different experiences, so each of us could work on the sides we excel or enjoy at, instead of working through hours of updates and things you don't want. Also I know we both live in different timezones, so we could both work at day, but in reality one of us would be doing night shift for the other. It's like a system: I wake up, work on projects, then sleep. You wake up, edit and finetune my stuff, create more new projects and go to sleep, then I could take over again, edit, and the cycle goes on. It's a really efficient way of collaborating. Which is why i'd like you to be part of PhantomMC.  

P.S: My friend said didn't want a third person in Hyperbole Studios, so instead, I've created a new studio called Zephyra Studios where we can collaborate. If your want to change the name im fine with with that since I dont even think Zephyra Studios is even a good name.

Modrinth: https://modrinth.com/organization/zephyra
GitHub: https://github.com/Zephyra-Studios

Website: Haven't created one yet

**Comment by NXTler** [comment]
Thanks for taking your time writing this detailed response.
I don't have much time right now for working on any Modpacks, and I'm not entirely sure if I want to make anymore. However, I greatly appreciate your offer and take it as a compliment, I will come back to it if I want to make more/larger Modpacks.
