### ISSUE TITLE
VMP (Very Many Players) with Krypton causes all recipes in the recipe guide book disappeared

### ISSUE THREAD

**Issue by SteveKunG** [astei/krypton#97]
More details are in here: https://github.com/RelativityMC/VMP-fabric/issues/36

To fix this I have to disable `use_multiple_netty_event_loops` on VMP side.

**Comment by astei** [comment]
Not only is VMP a dangerous, horribly tested ball of changes, this change is basically snake oil. It claims to "reduce DoS attacks" but in reality it likely makes them _worse_, since legitimate users are even less likely to be able to log in with this "optimization". In addition. _most_ mods don't expect the event loop to change underneath them, so I wouldn't be surprised if other mods break with this.

I'm not fixing this. Stop using mods of dubious quality.

**Comment by itsdinkd** [comment]
> Not only is VMP a dangerous, horribly tested ball of changes, this change is basically snake oil. It claims to "reduce DoS attacks" but in reality it likely makes them _worse_, since legitimate users are even less likely to be able to log in with this "optimization". In addition. _most_ mods don't expect the event loop to change underneath them, so I wouldn't be surprised if other mods break with this.
> 
> I'm not fixing this. Stop using mods of dubious quality.

Why are you shitting on the dev? I guess you think C2ME is also bad?
